### ISSUE TITLE
被ban的情况发生吗？

### ISSUE THREAD

**Issue by fyzhang** [bsns/dianping#1]
看到你这里没有使用代理IP，所以想问下有发生被BAN的情况吗？

**Comment by bsns** [comment]
开始测试、调试的时候有短暂被禁止访问过，后来采用了除去ip代理之外的常用方法，比如下载delay，用user-agent池，爬取了几万条，最长持续运行大概一两天的时间，也没有被封。

**Comment by siyecaoh** [comment]
您好，为什么我运行爬取不到数据，报错
 INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-05-21 09:11:59 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-05-21 09:11:59 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/Users/hhc/Downloads/dianping-master/dianping/spiders/dianpingspider.py", line 31, in start_requests
    yield Request(url, headers=self.headers)
  File "/Library/Python/2.7/site-packages/scrapy/http/request/__init__.py", line 39, in __init__
    self.headers = Headers(headers or {}, encoding=encoding)
  File "/Library/Python/2.7/site-packages/scrapy/http/headers.py", line 12, in __init__
    super(Headers, self).__init__(seq)
  File "/Library/Python/2.7/site-packages/scrapy/utils/datatypes.py", line 193, in __init__
    self.update(seq)
  File "/Library/Python/2.7/site-packages/scrapy/utils/datatypes.py", line 229, in update
    super(CaselessDict, self).update(iseq)
  File "/Library/Python/2.7/site-packages/scrapy/utils/datatypes.py", line 228, in <genexpr>
    iseq = ((self.normkey(k), self.normvalue(v)) for k, v in seq)
ValueError: too many values to unpack
2018-05-21 09:11:59 [scrapy.core.engine] INFO: Closing spider (finished)
2018-05-21 09:11:59 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 5, 21, 1, 11, 59, 529582),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'memusage/max': 51367936,
 'memusage/startup': 51367936,
 'start_time': datetime.datetime(2018, 5, 21, 1, 11, 59, 521874)}
2018-05-21 09:11:59 [scrapy.core.engine] INFO: Spider closed (finished)
